# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CellLine(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, depmap_id: str=None, ccle_name: str=None, aliases: List[str]=None, cosmic_id: str=None, sanger_id: str=None, primary_disease: str=None, subtype_disease: str=None, gender: str=None, source: str=None):  # noqa: E501
        """CellLine - a model defined in Swagger

        :param depmap_id: The depmap_id of this CellLine.  # noqa: E501
        :type depmap_id: str
        :param ccle_name: The ccle_name of this CellLine.  # noqa: E501
        :type ccle_name: str
        :param aliases: The aliases of this CellLine.  # noqa: E501
        :type aliases: List[str]
        :param cosmic_id: The cosmic_id of this CellLine.  # noqa: E501
        :type cosmic_id: str
        :param sanger_id: The sanger_id of this CellLine.  # noqa: E501
        :type sanger_id: str
        :param primary_disease: The primary_disease of this CellLine.  # noqa: E501
        :type primary_disease: str
        :param subtype_disease: The subtype_disease of this CellLine.  # noqa: E501
        :type subtype_disease: str
        :param gender: The gender of this CellLine.  # noqa: E501
        :type gender: str
        :param source: The source of this CellLine.  # noqa: E501
        :type source: str
        """
        self.swagger_types = {
            'depmap_id': str,
            'ccle_name': str,
            'aliases': List[str],
            'cosmic_id': str,
            'sanger_id': str,
            'primary_disease': str,
            'subtype_disease': str,
            'gender': str,
            'source': str
        }

        self.attribute_map = {
            'depmap_id': 'depmap_id',
            'ccle_name': 'ccle_name',
            'aliases': 'aliases',
            'cosmic_id': 'cosmic_id',
            'sanger_id': 'sanger_id',
            'primary_disease': 'primary_disease',
            'subtype_disease': 'subtype_disease',
            'gender': 'gender',
            'source': 'source'
        }

        self._depmap_id = depmap_id
        self._ccle_name = ccle_name
        self._aliases = aliases
        self._cosmic_id = cosmic_id
        self._sanger_id = sanger_id
        self._primary_disease = primary_disease
        self._subtype_disease = subtype_disease
        self._gender = gender
        self._source = source

    @classmethod
    def from_dict(cls, dikt) -> 'CellLine':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cell_line of this CellLine.  # noqa: E501
        :rtype: CellLine
        """
        return util.deserialize_model(dikt, cls)

    @property
    def depmap_id(self) -> str:
        """Gets the depmap_id of this CellLine.


        :return: The depmap_id of this CellLine.
        :rtype: str
        """
        return self._depmap_id

    @depmap_id.setter
    def depmap_id(self, depmap_id: str):
        """Sets the depmap_id of this CellLine.


        :param depmap_id: The depmap_id of this CellLine.
        :type depmap_id: str
        """

        self._depmap_id = depmap_id

    @property
    def ccle_name(self) -> str:
        """Gets the ccle_name of this CellLine.


        :return: The ccle_name of this CellLine.
        :rtype: str
        """
        return self._ccle_name

    @ccle_name.setter
    def ccle_name(self, ccle_name: str):
        """Sets the ccle_name of this CellLine.


        :param ccle_name: The ccle_name of this CellLine.
        :type ccle_name: str
        """

        self._ccle_name = ccle_name

    @property
    def aliases(self) -> List[str]:
        """Gets the aliases of this CellLine.


        :return: The aliases of this CellLine.
        :rtype: List[str]
        """
        return self._aliases

    @aliases.setter
    def aliases(self, aliases: List[str]):
        """Sets the aliases of this CellLine.


        :param aliases: The aliases of this CellLine.
        :type aliases: List[str]
        """

        self._aliases = aliases

    @property
    def cosmic_id(self) -> str:
        """Gets the cosmic_id of this CellLine.


        :return: The cosmic_id of this CellLine.
        :rtype: str
        """
        return self._cosmic_id

    @cosmic_id.setter
    def cosmic_id(self, cosmic_id: str):
        """Sets the cosmic_id of this CellLine.


        :param cosmic_id: The cosmic_id of this CellLine.
        :type cosmic_id: str
        """

        self._cosmic_id = cosmic_id

    @property
    def sanger_id(self) -> str:
        """Gets the sanger_id of this CellLine.


        :return: The sanger_id of this CellLine.
        :rtype: str
        """
        return self._sanger_id

    @sanger_id.setter
    def sanger_id(self, sanger_id: str):
        """Sets the sanger_id of this CellLine.


        :param sanger_id: The sanger_id of this CellLine.
        :type sanger_id: str
        """

        self._sanger_id = sanger_id

    @property
    def primary_disease(self) -> str:
        """Gets the primary_disease of this CellLine.


        :return: The primary_disease of this CellLine.
        :rtype: str
        """
        return self._primary_disease

    @primary_disease.setter
    def primary_disease(self, primary_disease: str):
        """Sets the primary_disease of this CellLine.


        :param primary_disease: The primary_disease of this CellLine.
        :type primary_disease: str
        """

        self._primary_disease = primary_disease

    @property
    def subtype_disease(self) -> str:
        """Gets the subtype_disease of this CellLine.


        :return: The subtype_disease of this CellLine.
        :rtype: str
        """
        return self._subtype_disease

    @subtype_disease.setter
    def subtype_disease(self, subtype_disease: str):
        """Sets the subtype_disease of this CellLine.


        :param subtype_disease: The subtype_disease of this CellLine.
        :type subtype_disease: str
        """

        self._subtype_disease = subtype_disease

    @property
    def gender(self) -> str:
        """Gets the gender of this CellLine.


        :return: The gender of this CellLine.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this CellLine.


        :param gender: The gender of this CellLine.
        :type gender: str
        """

        self._gender = gender

    @property
    def source(self) -> str:
        """Gets the source of this CellLine.


        :return: The source of this CellLine.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this CellLine.


        :param source: The source of this CellLine.
        :type source: str
        """

        self._source = source
