# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ExpressionValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, ensembl_gene: str=None, depmap_id: str=None, value: float=None):  # noqa: E501
        """ExpressionValue - a model defined in Swagger

        :param ensembl_gene: The ensembl_gene of this ExpressionValue.  # noqa: E501
        :type ensembl_gene: str
        :param depmap_id: The depmap_id of this ExpressionValue.  # noqa: E501
        :type depmap_id: str
        :param value: The value of this ExpressionValue.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'ensembl_gene': str,
            'depmap_id': str,
            'value': float
        }

        self.attribute_map = {
            'ensembl_gene': 'ensembl_gene',
            'depmap_id': 'depmap_id',
            'value': 'value'
        }

        self._ensembl_gene = ensembl_gene
        self._depmap_id = depmap_id
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'ExpressionValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The expression_value of this ExpressionValue.  # noqa: E501
        :rtype: ExpressionValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ensembl_gene(self) -> str:
        """Gets the ensembl_gene of this ExpressionValue.


        :return: The ensembl_gene of this ExpressionValue.
        :rtype: str
        """
        return self._ensembl_gene

    @ensembl_gene.setter
    def ensembl_gene(self, ensembl_gene: str):
        """Sets the ensembl_gene of this ExpressionValue.


        :param ensembl_gene: The ensembl_gene of this ExpressionValue.
        :type ensembl_gene: str
        """

        self._ensembl_gene = ensembl_gene

    @property
    def depmap_id(self) -> str:
        """Gets the depmap_id of this ExpressionValue.


        :return: The depmap_id of this ExpressionValue.
        :rtype: str
        """
        return self._depmap_id

    @depmap_id.setter
    def depmap_id(self, depmap_id: str):
        """Sets the depmap_id of this ExpressionValue.


        :param depmap_id: The depmap_id of this ExpressionValue.
        :type depmap_id: str
        """

        self._depmap_id = depmap_id

    @property
    def value(self) -> float:
        """Gets the value of this ExpressionValue.


        :return: The value of this ExpressionValue.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this ExpressionValue.


        :param value: The value of this ExpressionValue.
        :type value: float
        """

        self._value = value
