# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProteinArrayValueProtein(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, antibody_name: str=None, target_genes: List[str]=None):  # noqa: E501
        """ProteinArrayValueProtein - a model defined in Swagger

        :param antibody_name: The antibody_name of this ProteinArrayValueProtein.  # noqa: E501
        :type antibody_name: str
        :param target_genes: The target_genes of this ProteinArrayValueProtein.  # noqa: E501
        :type target_genes: List[str]
        """
        self.swagger_types = {
            'antibody_name': str,
            'target_genes': List[str]
        }

        self.attribute_map = {
            'antibody_name': 'antibody_name',
            'target_genes': 'target_genes'
        }

        self._antibody_name = antibody_name
        self._target_genes = target_genes

    @classmethod
    def from_dict(cls, dikt) -> 'ProteinArrayValueProtein':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The protein_array_value_protein of this ProteinArrayValueProtein.  # noqa: E501
        :rtype: ProteinArrayValueProtein
        """
        return util.deserialize_model(dikt, cls)

    @property
    def antibody_name(self) -> str:
        """Gets the antibody_name of this ProteinArrayValueProtein.


        :return: The antibody_name of this ProteinArrayValueProtein.
        :rtype: str
        """
        return self._antibody_name

    @antibody_name.setter
    def antibody_name(self, antibody_name: str):
        """Sets the antibody_name of this ProteinArrayValueProtein.


        :param antibody_name: The antibody_name of this ProteinArrayValueProtein.
        :type antibody_name: str
        """

        self._antibody_name = antibody_name

    @property
    def target_genes(self) -> List[str]:
        """Gets the target_genes of this ProteinArrayValueProtein.


        :return: The target_genes of this ProteinArrayValueProtein.
        :rtype: List[str]
        """
        return self._target_genes

    @target_genes.setter
    def target_genes(self, target_genes: List[str]):
        """Sets the target_genes of this ProteinArrayValueProtein.


        :param target_genes: The target_genes of this ProteinArrayValueProtein.
        :type target_genes: List[str]
        """

        self._target_genes = target_genes
