# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RnaiValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, entrez_gene_ids: List[int]=None, depmap_id: str=None, value: float=None):  # noqa: E501
        """RnaiValue - a model defined in Swagger

        :param entrez_gene_ids: The entrez_gene_ids of this RnaiValue.  # noqa: E501
        :type entrez_gene_ids: List[int]
        :param depmap_id: The depmap_id of this RnaiValue.  # noqa: E501
        :type depmap_id: str
        :param value: The value of this RnaiValue.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'entrez_gene_ids': List[int],
            'depmap_id': str,
            'value': float
        }

        self.attribute_map = {
            'entrez_gene_ids': 'entrez_gene_ids',
            'depmap_id': 'depmap_id',
            'value': 'value'
        }

        self._entrez_gene_ids = entrez_gene_ids
        self._depmap_id = depmap_id
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'RnaiValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The rnai_value of this RnaiValue.  # noqa: E501
        :rtype: RnaiValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def entrez_gene_ids(self) -> List[int]:
        """Gets the entrez_gene_ids of this RnaiValue.


        :return: The entrez_gene_ids of this RnaiValue.
        :rtype: List[int]
        """
        return self._entrez_gene_ids

    @entrez_gene_ids.setter
    def entrez_gene_ids(self, entrez_gene_ids: List[int]):
        """Sets the entrez_gene_ids of this RnaiValue.


        :param entrez_gene_ids: The entrez_gene_ids of this RnaiValue.
        :type entrez_gene_ids: List[int]
        """

        self._entrez_gene_ids = entrez_gene_ids

    @property
    def depmap_id(self) -> str:
        """Gets the depmap_id of this RnaiValue.


        :return: The depmap_id of this RnaiValue.
        :rtype: str
        """
        return self._depmap_id

    @depmap_id.setter
    def depmap_id(self, depmap_id: str):
        """Sets the depmap_id of this RnaiValue.


        :param depmap_id: The depmap_id of this RnaiValue.
        :type depmap_id: str
        """

        self._depmap_id = depmap_id

    @property
    def value(self) -> float:
        """Gets the value of this RnaiValue.


        :return: The value of this RnaiValue.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this RnaiValue.


        :param value: The value of this RnaiValue.
        :type value: float
        """

        self._value = value
